POST http://localhost:8000/users 
Content-Type: application/jsons

{
    "name": "John Doe",
    "email": "j@j.com",
    "password": "password"
}

###
POST http://localhost:8000/users/generate_token
Content-Type: application/json

{
    "email": "j@j.com",
    "password": "password"
}