// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

type Category struct {
	ID          string
	Name        string
	Description string
}

type Course struct {
	ID          string
	CategoryID  string
	Name        string
	Description string
	Price       string
}
